multList = ["Multiplication", "mult", "multiply", "Multiply", "m"]
divList = ["Division", "division", "div", "Div", "D", "d"]
addList = ["Addition", "addition", "add", "Add", "a", "A"]
subList = ["Subtraction", "subtraction", "sub", "Sub", "s", "S"]
yesList = ["Y", "y", "yes", "YES"]
noList = ["N", "n", "no", "NO"]